/*
 * Copyright 2026-present original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package grails.plugin.inertia.routes

import groovy.json.JsonOutput
import groovy.transform.CompileStatic

import grails.util.GrailsNameUtils

/**
 * Writes the routes as a JavaScript module with an object for each controller, named after its class, and a function for
 * each action.
 *
 * <p>An action function takes the URL parameters, as a single value, an array in the order of the template, or an
 * object by name, where the names that are not in the template become the query string. It returns the URL and the
 * default method of the action, which Inertia accepts wherever it takes a URL:</p>
 *
 * <pre>
 * import { OrganizationsController } from './routes'
 *
 * OrganizationsController.update(1)          // { url: '/organizations/1', method: 'put' }
 * OrganizationsController.update.post(1)     // { url: '/organizations/1', method: 'post' }
 * OrganizationsController.update.url(1)      // '/organizations/1'
 * OrganizationsController.index({ page: 2 }) // { url: '/organizations?page=2', method: 'get' }
 * </pre>
 *
 * <p>The routes of named URL mappings are exported by name in {@code named}, such as {@code named.showBook(1)}.</p>
 *
 * <p>The context path is exported as {@code contextPath}, for the URLs that are not controller actions, such as
 * {@code `${contextPath}/logout`}.</p>
 *
 * @since 4.1
 */
@CompileStatic
class RoutesModuleWriter {

    private static final String RUNTIME = '''\
const encode = (value, spansSegments) => spansSegments
    ? String(value).split('/').map(encodeURIComponent).join('/')
    : encodeURIComponent(String(value))

const parameterNames = (template) => [...template.matchAll(/\\{(\\w+)[*?]*\\}/g)].map((match) => match[1])

const url = (template, args = {}) => {
    const names = parameterNames(template)
    const values = args !== null && typeof args === 'object' && !Array.isArray(args)
        ? { ...args }
        : Object.fromEntries([args].flat().map((value, index) => [names[index], value]))
    const path = template.replace(/\\/?\\{(\\w+)(\\*?)(\\??)\\}/g, (segment, name, spansSegments, optional) => {
        const value = values[name]
        delete values[name]
        if (value === undefined || value === null || value === '') {
            if (optional) {
                return ''
            }
            throw new Error(`Missing route parameter "${name}" for ${template}`)
        }
        return segment.slice(0, segment.indexOf('{')) + encode(value, spansSegments)
    })
    const query = new URLSearchParams(Object.entries(values).filter(([, value]) => value !== undefined && value !== null))
        .toString()
    return contextPath + (path || '/') + (query ? `?${query}` : '')
}

const route = (template, methods) => {
    const action = (args) => ({ url: url(template, args), method: methods[0] })
    action.url = (args) => url(template, args)
    for (const method of methods) {
        action[method] = (args) => ({ url: url(template, args), method })
    }
    return action
}
'''

    /**
     * @param routes the routes to write
     * @param contextPath the context path of the application, which every URL starts with
     * @return the source of the module
     */
    String write(List<Route> routes, String contextPath) {
        final source = new StringBuilder()
        source << '// Generated by grails-inertia from the URL mappings of the application. Do not edit.\n\n'
        source << "export const contextPath = ${JsonOutput.toJson(contextPath ?: '')}\n\n"
        source << RUNTIME
        routes.findAll { !it.name }.groupBy { it.controller }.each { String controller, List<Route> controllerRoutes ->
            writeExport(source, GrailsNameUtils.getClassName(controller, 'Controller'), controllerRoutes.collectEntries { [(it.action): it] })
        }
        final namedRoutes = routes.findAll { it.name }
        if (namedRoutes) {
            writeExport(source, 'named', namedRoutes.collectEntries { [(it.name): it] })
        }
        source.toString()
    }

    private static void writeExport(StringBuilder source, String name, Map<String, Route> routes) {
        source << "\nexport const ${name} = {\n"
        routes.each { String key, Route route ->
            source << "    ${JsonOutput.toJson(key)}: route(${JsonOutput.toJson(route.template)}, ${JsonOutput.toJson(route.methods)}),\n"
        }
        source << '}\n'
    }
}
